### ISSUE TITLE
✨ Add build and test github workflow

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.CleanArchitecture#110]
Basic build and test workflow that is included in the template.

```[tasklist]
### Tasks
- [x] Repo - turn off template setting (as all files are included when you use a repo as a template
- [x] Build/test - make it a better first run experience for new users #211
- [x] Nuget config - include workflow files as part of nuget template
```

**Comment by danielmackay** [comment]
Sprint 5

**Comment by danielmackay** [comment]
@wicksipedia - what's the update on this?  Is there an outstanding PR?

**Comment by wicksipedia** [comment]
all merged and done
