### ISSUE TITLE
✨Minimal APIs + Result Pattern

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.CleanArchitecture#137]
https://www.linkedin.com/feed/update/urn:li:activity:7085136809080336384/?origin=SHARED_BY_YOUR_NETWORK
```[tasklist]
### Tasks
- [ ] ~Continue adding strongly typed support for all APIs~
- [x] Continue adding result support for all APIs
- [x] Consider migrating to ErrorOr
- [x] Consider tidying up boiler plate (i.e. repeated code between APIs)
- [x] Remove 'Strongly Typed APIs'
- [x] Add produces calls back APIs
- [x] Add results to Domain
```
