### ISSUE TITLE
✨ Publish a `ssw.adrs` dotnet new template

### ISSUE THREAD

**Issue by GordonBeeming** [SSWConsulting/SSW.CleanArchitecture#276]
Cc:

Hi 

### Pain

I just had to setup ADRs in a project, and although it was fairly quick with a couple of copy and pastes... this process could have been better

### Suggested Solution

Create a template that we can easily just run `dotnet new ssw-adrs` and get the basic layout with the first 2 ADRs (for markdown and log4brains) added and ready to go

### Acceptance Criteria
Acceptance Criteria defines the requirements that must be met for the story to be completed.  This is **WHAT** must be done.

See https://www.ssw.com.au/rules/acceptance-criteria.

1. On a **any project** I can run `dotnet new ssw-adrs` and commit with no additional changes
  - Configure my GitHub pages configuration and everything just works

### Tasks
Tasks help developers to track small bits of work needed to meet the ACs. This is **HOW** the work will be done.

```[tasklist]
- [ ] Create a new repository SSW.Templates.ADRs
- [ ] Add the base code needed to run the ADRs
- [ ] Publish a new nuget package which will install using the id `ssw-adrs`
- [ ] Done video
- [ ] Share to SSW Developers DL
```

### Screenshots

Thanks!

**Comment by GordonBeeming** [comment]
@danielmackay @william-liebenberg I'm happy to work on this as per our conversation a couple of weeks back

**Comment by GordonBeeming** [comment]
I can also update this SSW CA repo to use the publish github pages, instead of copy to branch that we're doing now if you want
Shown in this video 😅 
https://youtu.be/5HcmbFIzS_s?si=bCGCgj4T4JXjH37N&t=614
