### ISSUE TITLE
DDD Refactor

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.CleanArchitecture#290]
The new domain is based around heroes and will provide the following functionality:

### Heros
- Get Heroes - `GET /heroes`
- Update a Hero - `PUT /heroes`
- Create a Hero - `POST /heroes`

### Teams
- Create a team - `POST /teams`
- Get teams - `GET /teams`
- Add a hero to a team - `POST /teams/ID/hero`
- Execute a mission for a team - `POST /teams/ID/execute-mission`
- Complete a mission for a team - `POST /teams/ID/complete-mission`

```[tasklist]
### Tasks
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/244
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/285
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/262
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/261
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/pull/286
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/287
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/283
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/295
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/282
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/291
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/316
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/292
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/317
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/318
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/319
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/263
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/320
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/264
- [ ] https://github.com/SSWConsulting/SSW.CleanArchitecture/issues/293
```

**Comment by danielmackay** [comment]
All PBI's done@
