### ISSUE TITLE
✨ Complete CRUD operations for Heroes and Teams

### ISSUE THREAD

**Issue by jernejk** [SSWConsulting/SSW.CleanArchitecture#354]
Cc:

Hi,

### Pain
When I navigate to `/swagger`, there are missing CRUD operations like deleting a hero/team and fetching individual hero. This could also be an interesting way to demonstrate soft-delete feature.

### Suggested Solution
Add missing endpoints and their implementation.

### Acceptance Criteria
Acceptance Criteria defines the requirements that must be met for the story to be completed.  This is **WHAT** must be done.

See https://www.ssw.com.au/rules/acceptance-criteria.

1. Have full CRUD operations for heroes and teams

### Tasks
Tasks help developers to track small bits of work needed to meet the ACs. This is **HOW** the work will be done.

```[tasklist]
- [ ] Add `GET /api/heroes/{heroId}`
- [ ] Add `DELETE /api/heroes/{heroId}`
- [ ] Add `DELETE /api/teams/{heroId}`
```

Thanks!

**Comment by danielmackay** [comment]
There are extra API's that still all need to be added

**Comment by danielmackay** [comment]
Won't do - there is no need to build out all these extra APIs in a template. Doing so will only create MORE code to remove before adding custom functionality.
