### ISSUE TITLE
♻️ Review Architecture Test Library

### ISSUE THREAD

**Issue by danielmackay** [SSWConsulting/SSW.CleanArchitecture#429]
This library does not seem easy to use. There are several scenarios, that we couldn't get it to work for.

### Key Architecture Scenarios
- [x] Check inner layers are not referencing outer layers
- [x] Check the majority of the Domain inherit from certain base classes (e.g. aggregate, valueobject, entity, etc)
- [x] Check outer layers are not bypassing inner layers (e.g. not calling domain code directly from the web layer)
- [x] Check correct suffixes or prefixes are used (e.g xxxCommandHandler)

### Resources
- https://medium.com/@v.cheshmy/architecture-tests-in-net-d95192faf2dd
- https://www.milanjovanovic.tech/blog/enforcing-software-architecture-with-architecture-tests

### Tasks

```[tasklist]
- [x] Create a list of scenarios
- [x] Evaluate current arch test framework
- [x] Consider switching to alternative
```
